version: '3'

services:
  app:
    container_name: 'lottey-app'
    build:
      context: .docker
      dockerfile: app.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app/next-project
    environment:
      CSR_VIEW_URI: 'http://lottery.nutfes.net'
    command: bash -c 'npm run build && npm run start'
    depends_on:
      - api
    tty: true

  api:
    container_name: 'lottey-api'
    build:
      context: .docker
      dockerfile: api.Dockerfile
    volumes:
      - ./api:/go/src/app/api
    env_file:
      - lottery.env
    ports:
      - '1323:1323'
    command: './start.sh'
