version: '3'

services:
  nfc:
    container_name: 'ST-NFC'
    build:
      context: .docker
      dockerfile: nfc.Dockerfile
    volumes:
      - ./nfc:/nfc
      - /dev/bus/usb:/dev/bus/usb:ro
    command: sh -c "python -m nfc && python main.py"
    env_file:
      - lottery.env
    privileged: true
