version: '3'

services:
  api:
    container_name: 'ST-API'
    build:
      context: .docker
      dockerfile: api.Dockerfile
    volumes:
      - ./api:/var/www/html
    ports:
      - '8000:8000'
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - lottery.env

  app:
    container_name: 'ST-APP'
    build:
      context: .docker
      dockerfile: app.Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - ./app:/app/next-project
    command: 'npm run start'
    env_file:
      - lottery.env
    depends_on:
      - api
