version: '3'

services:
  api:
    container_name: FastAPI
    build: ./Fast-API/docker
    volumes:
      - ./Fast-API:/var/www/html
    ports:
      - "8000:8000"
    command: uvicorn run:app --reload --host 0.0.0.0 --port 8000