version: '3'

services:
  api:
    container_name: "ST-API"
    build: ./docker/fastapi
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  web:
    container_name: "ST-WEB"
    build: ./docker/node
    ports:
      - "8888:8888"
    volumes:
      - ./app:/usr/src/app