version: '3'

services:
  app:
    container_name: FastAPI
    build: ./Fast-API/docker
    volumes:
      - ./Fast-API:/var/www/html
    ports:
      - "8000:8000"
    command: uvicorn run:app --reload --host 0.0.0.0 --port 8000

  view:
    build:
      context: ./next-view
      dockerfile: ./Dockerfile
    volumes:
      - ./next-view:/usr/src/app
    command: sh -c "cd sample-app && npm run dev"
    ports:
      - "3000:3000"