version: '3'

services:
  api:
    container_name: 'ST-API'
    build:
      context: .docker
      dockerfile: go.Dockerfile
    volumes:
      - ./go_api:/usr/local/go/src/api
    env_file:
      - lottery.env
    ports:
      - '1323:1323'
    command: './start.sh'

  app:
    container_name: 'ST-APP'
    build:
      context: .docker
      dockerfile: app.Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - ./app:/app/next-project
    command: 'npm run dev'
    env_file:
      - lottery.env
    depends_on:
      - api
