version: '3'

services:
  api:
    container_name: 'ST-API'
    build:
      context: .docker
      dockerfile: api.Dockerfile
    volumes:
      - ./api:/var/www/html
    ports:
      - '8000:8000'
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    environment:
      ST_USER: admin
      ST_PASS: password

  app:
    container_name: 'ST-APP'
    build:
      context: .docker
      dockerfile: app.Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - ./app:/app/next-project
    command: 'npm run dev'
    environment:
      SSR_API_URI: 'http://lottery-api.nutfes.net/api'
      CSR_API_URI: 'http://lottery-api.nutfes.netapi'
    depends_on:
      - api
