version: '3'

services:
  api:
    container_name: 'ST-API'
    build:
      context: .docker
      dockerfile: api.Dockerfile
    volumes:
      - ./api:/var/www/html
    ports:
      - '8000:8000'
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    environment:
      CLIENT_ID: admin
      CLIENT_SECRET: password

  app:
    container_name: 'ST-APP'
    build:
      context: .docker
      dockerfile: app.Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - ./app:/app/next-project
    command: 'npm run dev'
    environment:
      CLIENT_ID: admin
      CLIENT_SECRET: password
      SSR_API_URI: 'http://api:8000/api'
      CSR_API_URI: 'http://api:8000/api'
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASSWORD: password
      WS_API_URI: ws://api:8000/ws
    depends_on:
      - api

  nfc:
    container_name: 'ST-NFC'
    build:
      context: .docker
      dockerfile: nfc.Dockerfile
    volumes:
      - ./nfc:/nfc
      - /dev/bus/usb:/dev/bus/usb:ro
    command: sh -c "python -m nfc && python main.py"
    environment:
      VENDOR: 054c
      PRODUCT: 06c1
      PLACE_ID: 1
      CLIENT_ID: admin
      CLIENT_SECRET: password
      SSR_API_URI: http://api:8000/api
      WS_API_URI: ws://api:8000/ws
    privileged: true
    depends_on:
      - api
