version: '3'

services:
  cloudflare:
    container_name: "lottery-cloudflare"
    image: 'cloudflare/cloudflared:latest'
    volumes: ['./cloudflare/prod:/home/nonroot/.cloudflared']
    command: tunnel run

  api:
    container_name: 'lottery-api'
    build:
      context: '.docker'
      dockerfile: 'api.Dockerfile'
    ports: ['1323:1323']
    volumes: ['./api:/go/src/app/api']
    env_file: ['lottery.env']
    command: './start.sh'

  app:
    container_name: 'lottery-app'
    build:
      context: '.docker'
      dockerfile: 'app.Dockerfile'
    ports: ['3000:3000']
    volumes: ['./app:/app/next-project']
    env_file: ['lottery.env']
    command: bash -c 'npm run build && npm run start'
    depends_on: ['api']
