// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users":{
            "get":{
                "description":"全ユーザーの取得",
                "responses":{
                    "200":{
                        "description":"OK",
                        "schema":{
                            "type":"array",
                        }
                    }
                }
            },
            "post":{
                "description":"ユーザーの作成",
                "parameters": [
                    {
                        "name": "name",
                        "type": "string",
                        "in": "query",
                        "description": "ユーザー名",
                    },
                    {
                        "name": "number",
                        "type": "integer",
                        "in": "query",
                        "description": "ユーザーの学籍番号",
                    }
                ],
                "responses":{
                    "200":{
                        "description":"Created User",
                    },
                }
            }
        },
        "/users/{id}":{
            "get":{
                "description":"IDを指定してユーザーの取得",
                "parameters": [
                    {
                        "name": "id",
                        "type": "integer",
                        "in": "path",
                        "description": "ユーザーID",
                        "required": true
                    }
                ],
                "responses":{
                    "200":{
                        "description":"OK",
                        "schema":{
                            "type":"object",
                        }
                    }
                }
            },
            "put":{
                "description":"IDを指定してユーザーの更新",
                "parameters": [
                    {
                        "name": "id",
                        "type": "integer",
                        "in": "path",
                        "description": "ユーザーID",
                        "required": true
                    },
                    {
                        "name": "name",
                        "type": "string",
                        "in": "query",
                        "description": "ユーザー名",
                    },
                    {
                        "name": "number",
                        "type": "integer",
                        "in": "query",
                        "description": "ユーザーの学籍番号",
                    }
                ],
                "responses":{
                    "200":{
                        "description":"OK",
                        "schema":{
                            "type":"object",
                        }
                    }
                }
            },
            "delete":{
                "description":"IDを指定してユーザーの削除",
                "parameters": [
                    {
                        "name": "id",
                        "type": "integer",
                        "in": "path",
                        "description": "ユーザーID",
                        "required": true
                    }
                ],
                "responses":{
                    "200":{
                        "description":"OK",
                    }
                }
            }
        },
        "/admins":{
            "get":{
                "description":"全アドミンユーザの取得",
                "responses":{
                    "200":{
                        "description":"OK",
                        "schema":{
                            "type":"array",
                        }
                    }
                }
            },
            "post":{
                "description":"アドミンユーザーの作成",
                "parameters": [
                    {
                        "name": "name",
                        "type": "string",
                        "in": "query",
                        "description": "アドミンユーザー名",
                    },
                    {
                        "name": "email",
                        "type": "string",
                        "in": "query",
                        "description": "アドミンユーザーのメールアドレス",
                    },
                    {
                        "name": "password",
                        "type": "string",
                        "in": "query",
                        "description": "アドミンユーザーのパスワード",
                    }
                ],
                "responses":{
                    "200":{
                        "description":"Created Admin",
                    },
                }
            }
        },
        "/admins/{id}":{
            "get":{
                "description":"IDを指定してアドミンユーザーの取得",
                "parameters": [
                    {
                        "name": "id",
                        "type": "integer",
                        "in": "path",
                        "description": "アドミンユーザーID",
                        "required": true
                    }
                ],
                "responses":{
                    "200":{
                        "description":"OK",
                        "schema":{
                            "type":"object",
                        }
                    }
                }
            },
            "put":{
                "description":"IDを指定してアドミンユーザーの更新",
                "parameters": [
                    {
                        "name": "id",
                        "type": "integer",
                        "in": "path",
                        "description": "アドミンユーザーID",
                        "required": true
                    },
                    {
                        "name": "name",
                        "type": "string",
                        "in": "query",
                        "description": "アドミンユーザー名",
                    },
                    {
                        "name": "email",
                        "type": "string",
                        "in": "query",
                        "description": "アドミンユーザーのメールアドレス",
                    },
                    {
                        "name": "password",
                        "type": "string",
                        "in": "query",
                        "description": "アドミンユーザーのパスワード",
                    }
                ],
                "responses":{
                    "200":{
                        "description":"OK",
                        "schema":{
                            "type":"object",
                        }
                    }
                }
            },
            "delete":{
                "description":"IDを指定してアドミンユーザーの削除",
                "parameters": [
                    {
                        "name": "id",
                        "type": "integer",
                        "in": "path",
                        "description": "アドミンユーザーID",
                        "required": true
                    }
                ],
                "responses":{
                    "200":{
                        "description":"OK",
                    }
                }
            },
        },
    },
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1323",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "NUTFes Lottery API",
	Description:      "NUTFes Lottery API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
